export const PERMISSIONS = {
  // MANAGE
  CAN_MANAGE_PERMISSIONS: "CAN_MANAGE_PERMISSIONS",
  CAN_MANAGE_STUDENTS: "CAN_MANAGE_STUDENTS",

  // ADD / REQUEST
  CAN_REQUEST_TENANT: "CAN_REQUEST_TENANT",
  CAN_ADD_SCHEME: "CAN_ADD_SCHEME",
  CAN_ADD_STUDENT: "CAN_ADD_STUDENT",
  CAN_JOIN_SCHOOL: "CAN_JOIN_SCHOOL",
  CAN_APPLY_SCHOOL: "CAN_APPLY_SCHOOL",

  // VIEWS
  CAN_VIEW_DASHBOARD: "CAN_VIEW_DASHBOARD",
  CAN_VIEW_LESSON_PLAN: "CAN_VIEW_LESSON_PLAN",
  CAN_VIEW_SCHEME: "CAN_VIEW_SCHEME",
  CAN_VIEW_DRAFT: "CAN_VIEW_DRAFT",

  CAN_VIEW_LIBRARY: "CAN_VIEW_LIBRARY",
  CAN_VIEW_ATTENDANCE: "CAN_VIEW_ATTENDANCE",
  CAN_VIEW_CLASSES: "CAN_VIEW_CLASSES",
  CAN_VIEW_EXAMS: "CAN_VIEW_EXAMS",
  CAN_VIEW_FEES: "CAN_VIEW_FEES",
  CAN_VIEW_MESSAGES: "CAN_VIEW_MESSAGES",
  CAN_VIEW_MEETINGS: "CAN_VIEW_MEETINGS",
  CAN_VIEW_CALENDAR: "CAN_VIEW_CALENDAR",



  CAN_VIEW_SETTINGS: "CAN_VIEW_SETTINGS",
} as const;


export type PermissionKey = keyof typeof PERMISSIONS;
export type PermissionCode = typeof PERMISSIONS[PermissionKey];
