import { LessonPlan } from "@/dto/lessonPlan.dto";

export const initialLessonPlans: LessonPlan[] = [
  {
    id: "1",
    school_name: "casa",
    teacher: "casto",
    class: "Grade 8",
    subject: "Mathematics",
    date: "12/12/2024",
    time: "10:40",
    registered_girls: 42,
    registered_boys: 23,
    present_girls: 34,
    present_boys: 23,
    main_competence: "Quadratics",
    specific_competence: "deep Algebra",
    main_activity: "Add algrabra",
    specific_activity: "Add algebra in math",
    teaching_resources: "compass",
    references: "nyambari nyangwine",
    steps: [
      {
        id: "12",
        stage: "sample",
        time_minutes: "sample",
        specific_activity: "sample",
        teaching_activities: "sample",
        learning_activities: "sample",
        assessment_criteria: "sample",
      }
    ],
    remarks: "Good",
    status: "completed",
  },
  {
    id: "2",
    school_name: "casa",
    teacher: "casto",
    class: "casa school",
    subject: "Math",
    date: "12/12/2024",
    time: "10:40",
    registered_girls: 42,
    registered_boys: 23,
    present_girls: 34,
    present_boys: 23,
    main_competence: "Algebra",
    specific_competence: "deep Algebra",
    main_activity: "Add algrabra",
    specific_activity: "Add algebra in math",
    teaching_resources: "compass",
    references: "nyambari nyangwine",
    steps: [],
    remarks: "Good",
    status: "completed",
  },
  {
    id: "3",
    school_name: "casa",
    teacher: "casto",
    class: "casa school",
    subject: "Math",
    date: "12/12/2024",
    time: "10:40",
    registered_girls: 42,
    registered_boys: 23,
    present_girls: 34,
    present_boys: 23,
    main_competence: "Algebra",
    specific_competence: "deep Algebra",
    main_activity: "Add algrabra",
    specific_activity: "Add algebra in math",
    teaching_resources: "compass",
    references: "nyambari nyangwine",
    steps: [],
    remarks: "Good",
    status: "pending",
  },
  {
    id: "4",
    school_name: "casa",
    teacher: "casto",
    class: "casa school",
    subject: "Math",
    date: "12/12/2024",
    time: "10:40",
    registered_girls: 42,
    registered_boys: 23,
    present_girls: 34,
    present_boys: 23,
    main_competence: "Algebra",
    specific_competence: "deep Algebra",
    main_activity: "Add algrabra",
    specific_activity: "Add algebra in math",
    teaching_resources: "compass",
    references: "nyambari nyangwine",
    steps: [],
    remarks: "Good",
    status: "pending",
  },
];
